spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false

logging:
  level:
    com.example.deliveryservice: INFO
    org.springframework: WARN

microservice:
  auth-service:
    endpoints:
      endpoint:
        uri: http://localhost:8080/validate

server:
  port: 0 