microservice:
  auth-service:
    endpoints:
      endpoint:
        uri: http://auth-service/auth/validateToken 

spring:
  application:
    name: delivery-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true 